"""
Main agent entrypoint: given a raw incoming customer message, produces
{intent, confidence, draft_reply, escalate, escalation_reason, retrieved_precedent}.

This is the single function the eval harness calls per example, and the
same function a real deployment would call per incoming ticket.
"""
from data_loader import clean_text
from intents import classify_intent
from escalation import decide_escalation
from reply_drafter import draft_reply


class SupportAgent:
    def __init__(self, retrieval_index, k_precedents: int = 3):
        self.retrieval_index = retrieval_index
        self.k_precedents = k_precedents

    def handle(self, raw_message: str) -> dict:
        message = clean_text(raw_message)

        intent_result = classify_intent(message)
        intent = intent_result["intent"]
        confidence = float(intent_result.get("confidence", 0.5))

        precedents = self.retrieval_index.query(message, k=self.k_precedents, intent=intent)
        top_sim = precedents[0]["similarity"] if precedents else 0.0

        escalation = decide_escalation(
            message=message, intent=intent, confidence=confidence,
            retrieval_top_similarity=top_sim,
        )

        # Even escalated messages get a draft reply — a human reviewer benefits
        # from a starting point rather than a blank page. See decision log.
        reply = draft_reply(message, intent, precedents)

        return {
            "input_message": raw_message,
            "cleaned_message": message,
            "intent": intent,
            "intent_confidence": confidence,
            "intent_reasoning": intent_result.get("reasoning", ""),
            "retrieved_precedent": precedents,
            "draft_reply": reply,
            "escalate": escalation["escalate"],
            "escalation_reason": escalation["reason"],
        }


if __name__ == "__main__":
    import sys
    import os
    import pandas as pd
    from data_loader import load_raw, build_pairs
    from retrieval import RetrievalIndex

    # Path resolved relative to this file's location, NOT the current working
    # directory — so this works whether you run it from the project root
    # (`python src/agent.py ...`) or from inside src/ (`python agent.py ...`).
    PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    DATA_DIR = os.path.join(PROJECT_ROOT, "data")

    # Prefer the CLEANED pairs (English-only, non-fragment) if they've been
    # generated by cleaning/clean_data.py — this keeps retrieval grounding
    # consistent with the golden set, which is also sampled from the cleaned
    # data. Falls back to rebuilding from raw twcs.csv, then to mock data.
    cleaned_pairs_path = os.path.join(DATA_DIR, "amazon_pairs_cleaned.csv")
    real_data_path = os.path.join(DATA_DIR, "twcs.csv")
    mock_data_path = os.path.join(DATA_DIR, "mock_twitter_support.csv")

    if os.path.exists(cleaned_pairs_path):
        print(f"[agent] Using cleaned pairs: {cleaned_pairs_path}")
        pairs = pd.read_csv(cleaned_pairs_path)
        cache_path = os.path.join(DATA_DIR, "embedding_cache_cleaned.npz")
    else:
        if os.path.exists(real_data_path):
            data_path = real_data_path
            print(f"[agent] Cleaned pairs not found; using real dataset: {data_path}")
        else:
            data_path = mock_data_path
            print(f"[agent] Real dataset not found at {real_data_path}; "
                  f"using mock data instead: {data_path}")
        raw = load_raw(data_path)
        pairs = build_pairs(raw)
        cache_path = os.path.join(DATA_DIR, "embedding_cache.npz")

    print(f"[agent] Built retrieval index from {len(pairs)} historical reply pairs.")
    index = RetrievalIndex(pairs, cache_path=cache_path)
    agent = SupportAgent(index)

    test_message = sys.argv[1] if len(sys.argv) > 1 else \
        "My order has been late for a week and nobody is responding!"

    # NOTE: this call requires GROQ_API_KEY set; see README.
    result = agent.handle(test_message)
    import json
    print(json.dumps(result, indent=2, default=str))